import type { Metadata } from "next";
import "./globals.css";
import { BalanceProvider } from "./contexts/BalanceContext";
import { SeedInventoryProvider } from "./contexts/SeedsInventoryContext";

export const metadata: Metadata = {
  title: "Example Project",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <BalanceProvider>
          <SeedInventoryProvider>
            {children}
          </SeedInventoryProvider>
        </BalanceProvider>
      </body>
    </html>
  );
}
