import type { Metadata } from "next";
import "./globals.css";
import { BalanceProvider } from "./contexts/BalanceContext";

export const metadata: Metadata = {
  title: "Example Project",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html>
      <body>
        <BalanceProvider>
          {children}
        </BalanceProvider>
      </body>
    </html>
  );
}
